version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./Public:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XerecaAzeda123!
      MYSQL_DATABASE: php_poo
      MYSQL_USER: root
      MYSQL_PASSWORD: XerecaAzeda123!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
