version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8081:8081"
    volumes:
      - ../Crud-PHP-POO:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "XerecaAzeda123!"  # Senha do usuário root
      MYSQL_DATABASE: "php_poo"  # Banco de dados a ser criado
    ports:
      - "3307:3306"  # Mapeando a porta 3307 do host para a porta 3306 do container
    volumes:
      - db-data:/var/lib/mysql  # Persistência dos dados do MySQL
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
